apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelp-camp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SrikanthKotipalli0209/EKS-3tire_Application.git
    targetRevision: main
    path: Manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: webapps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
